# Uncomment the following line to enable the OLED Display
CONFIG_ZMK_DISPLAY=y

# Enable Bluetooth for split communication and power
CONFIG_BT=y

# Enable USB as default
CONFIG_ZMK_BLE=y

# Enable Deep Sleep
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000   # 15 min → deep sleep (ms)
CONFIG_ZMK_IDLE_TIMEOUT=60000          # 1 min → idle (ms)
